/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmsys;

import java.util.Locale;

/**
 *
 * @author Miracle_Baba
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public dashboard() {
        initComponents();
    }
    String uname;
    int acctnum;
    public dashboard(String name, int num) {
        initComponents();
        uname = name;
        AcctName.setText(AcctName.getText()+ " " +uname.toUpperCase());
        
        acctnum = num;
        AcctNumber.setText(AcctNumber.getText()+" "+acctnum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Withdraw = new javax.swing.JButton();
        btn_Transfer = new javax.swing.JButton();
        btn_Balance = new javax.swing.JButton();
        btn_Deposit = new javax.swing.JButton();
        btn_Pin = new javax.swing.JButton();
        btn_History = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AcctName = new javax.swing.JLabel();
        AcctNumber = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("ACCOUNT NUMBER:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setUndecorated(true);
        setResizable(false);

        btn_Withdraw.setText("WITHDRAW");
        btn_Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WithdrawActionPerformed(evt);
            }
        });

        btn_Transfer.setText("TRANSFER");
        btn_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TransferActionPerformed(evt);
            }
        });

        btn_Balance.setText("CHECK BALANCE");
        btn_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BalanceActionPerformed(evt);
            }
        });

        btn_Deposit.setText("DEPOSIT");
        btn_Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DepositActionPerformed(evt);
            }
        });

        btn_Pin.setText("CHANGE PIN");
        btn_Pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PinActionPerformed(evt);
            }
        });

        btn_History.setText("<html> TRANSACTION </br> HISTORY </html>");
        btn_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HistoryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("AFRI-LAND BANK");

        AcctName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AcctName.setText("ACCOUNT NAME:");

        AcctNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        AcctNumber.setText("ACCOUNT NUMBER:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_History, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AcctName)
                .addGap(103, 103, 103)
                .addComponent(AcctNumber)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcctName)
                    .addComponent(AcctNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_History, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HistoryActionPerformed
        // TODO add your handling code here:
        history his = new history();
        his.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HistoryActionPerformed

    private void btn_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BalanceActionPerformed
        // TODO add your handling code here:
        balance bal = new balance(acctnum, uname);
        bal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BalanceActionPerformed

    private void btn_DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DepositActionPerformed

    private void btn_WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WithdrawActionPerformed
        // TODO add your handling code here:
        withdraw wd = new withdraw(acctnum, uname);
        wd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_WithdrawActionPerformed

    private void btn_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TransferActionPerformed
        // TODO add your handling code here:
        transfer trans = new transfer();
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_TransferActionPerformed

    private void btn_PinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PinActionPerformed
        // TODO add your handling code here:
        changePin pin = new changePin();
        pin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_PinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcctName;
    private javax.swing.JLabel AcctNumber;
    private javax.swing.JButton btn_Balance;
    private javax.swing.JButton btn_Deposit;
    private javax.swing.JButton btn_History;
    private javax.swing.JButton btn_Pin;
    private javax.swing.JButton btn_Transfer;
    private javax.swing.JButton btn_Withdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
