/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Miracle_Baba
 */
public class withdraw extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public withdraw() {
        initComponents();
    }
    
    int acctnum;
    String uname;
    public withdraw(int num, String name){
        initComponents();
        
        uname = name;
        acctnum = num;       
        Lbl_AcctNum.setText(""+acctnum);
        
        getBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Withdraw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lbl_Balance = new javax.swing.JLabel();
        Lbl_AcctNum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        withdrawAmt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setUndecorated(true);
        setResizable(false);

        btn_Withdraw.setText("WITHDRAW");
        btn_Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WithdrawActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("AFRI-LAND BANK");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("ACCOUNT NUMBER:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("ACCOUNT BALANCE:");

        Lbl_Balance.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        Lbl_Balance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lbl_Balance.setForeground(new java.awt.Color(255, 0, 0));
        Lbl_Balance.setText("CFA");
        Lbl_Balance.setOpaque(true);

        Lbl_AcctNum.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        Lbl_AcctNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lbl_AcctNum.setForeground(new java.awt.Color(255, 0, 0));
        Lbl_AcctNum.setText("CFA");
        Lbl_AcctNum.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("AMOUNT");

        withdrawAmt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("WITHDRAW");
        jLabel2.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmsys/kisspng-finger-line-angle-white-clip-art-5b3c70645a1739.937671591530687588369.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawAmt)
                    .addComponent(Lbl_AcctNum, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lbl_AcctNum))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Lbl_Balance))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(withdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btn_Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new dashboard(uname, Integer.valueOf(Lbl_AcctNum.getText())).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

        Connection Con = null;
        PreparedStatement pst = null;
        ResultSet Rs = null;
        Statement St; 
        
        String url = "jdbc:mysql://localhost:3306/atm_system";
        String username = "root";
        String password ="";
        
    private void btn_WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WithdrawActionPerformed
        // TODO add your handling code here:
    try{
            String cmd = "SELECT isSaving FROM bacnkusers WHERE AcctNo = '"+Integer.valueOf(Lbl_AcctNum.getText())+"' ";
            Con = DriverManager.getConnection(url, username, password);
            pst = Con.prepareStatement(cmd);
            Rs = pst.executeQuery();
            
//            Boolean isSaving = Rs.getBoolean(3);
            
        if(Rs.next() && Rs.getInt("isSaving")==1)
        {
            JOptionPane.showMessageDialog(this, "Sorry this is a Savings Account");

        }
        else
        {        
               
                if(withdrawAmt.getText().isEmpty() || Integer.valueOf(withdrawAmt.getText()) < 500){
                    JOptionPane.showMessageDialog(this, "You cannot withdraw below 500FCFA");
                }
                else if(Integer.valueOf(withdrawAmt.getText()) > Integer.valueOf(Lbl_Balance.getText())) {
                    JOptionPane.showMessageDialog(this, "Insufficient Balance");
                }
                else {
                    String query = "UPDATE bacnkusers SET Balance=? WHERE AcctNo='"+Integer.valueOf(Lbl_AcctNum.getText())+"' ";
                    try{
                        pst = Con.prepareStatement(query);
                        int newBal = Integer.valueOf(Lbl_Balance.getText()) - Integer.valueOf(withdrawAmt.getText());
                        pst.setInt(1, newBal);

                        if(pst.executeUpdate()==1)
                        {

                            JOptionPane.showMessageDialog(this, "Withdraw successfull");
                             Lbl_Balance.setText(""+newBal);
                             getBalance();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Failed to Withdraw");                
                            }

                        }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(this, e);
                    }
                }
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
                }
    }//GEN-LAST:event_btn_WithdrawActionPerformed
        
        
        private void getBalance(){
            try {
                String sql = "SELECT * FROM bacnkusers WHERE AcctNo = '"+Integer.valueOf(Lbl_AcctNum.getText())+"' ";
                Con = DriverManager.getConnection(url, username, password);
                pst = Con.prepareStatement(sql);
//                pst.setString(1, AcctNum.getText());
//                pst.setString(2, AcctPin.getText());
                Rs = pst.executeQuery(sql);
                
                int oldBal;
                if(Rs.next()){                   
                     oldBal = Rs.getInt(7);
                     Lbl_Balance.setText(""+oldBal);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid Login Details");
                }               
            } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex);
            }
        }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_AcctNum;
    private javax.swing.JLabel Lbl_Balance;
    private javax.swing.JButton btn_Withdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField withdrawAmt;
    // End of variables declaration//GEN-END:variables
}
